PNDA-4502: Create example applications for Flink
pndaproject/example-applications pull request #52
Opened 2018-06-10 18:49 UTC by GaneshManal

# Problem Statement:
PNDA-4502: Create example applications for Flink

# Changes:
Added the java example application for flink illustrating -
- Flink Java API
- Flink Windows
- Flink Triggers
- Flink Connectors - AVRO Support
- Flink Kafka Connector

# Test details
RHEL - PICO - CDH & HDP

2018-06-21 15:27 UTC, willis27 requested changes
Saw this too from log.
"java.lang.ClassNotFoundException: org.apache.flink.metrics.graphite.GraphiteReporter" which may related to PNDA-4548 PR. Need to revisit after that PR is merged.

2018-06-21 15:27 UTC, willis27 commented on flink-streaming-host-network-data-usage/data-source/src/main/resources/requirements.txt
> +kafka-python==0.4.2
Change versions for consistency of other example streaming apps. 
see: https://github.com/pndaproject/example-applications/blob/develop/traffic-loss-analysis-app/data-source/resources/requirements.txt

2018-06-21 15:27 UTC, willis27 commented on flink-streaming-host-network-data-usage/data-source/src/main/resources/src.py
> +        # print('AVRO Data: ' + extra_bytes + raw_bytes)
remove commented code line

2018-06-21 15:27 UTC, willis27 commented on flink-streaming-host-network-data-usage/README.md
> +It will also create `data-source-1.0.0.tar.gz` in in the `data-source/target` directory. This can be used as a sample data source.
'in in'?

2018-06-21 15:27 UTC, willis27 commented on flink-streaming-host-network-data-usage/README.md
> +The example stream processing application shows an example of an application that can be deployed using the PNDA Deployment Manager. (See the `platform-deployment-manager` project for details.)
use link to "platform-deployment-manager" repo?

2018-06-25 06:43 UTC, GaneshManal commented
review changes are done.

2018-06-25 08:59 UTC, merged